GameNetworking/NetworkSynchronizer

networked_controller.cpp
networked_controller.h
scene_synchronizer.cpp
scene_synchronizer.h

Port of: https://github.com/GodotNetworking/network_synchronizer/pull/1
Adds the possibility to implement Bots (Characters controlled by the AI)
This commit introduces the concept of controlled by the server on
the NetworkedController: When this property is set to true the
server collects the inputs and process the controlled object -> all the
other clients will see it as a doll.
Notice, it's possible to change server_controlled at runtime to switch
from player controller to AI controlled and vice versa.

Adds the possibility to implement Bots (Characters controlled by the AI)

---

networked_controller.cpp
networked_controller.h

Backport of https://github.com/GodotNetworking/network_synchronizer/pull/4

fix for server performing redundant operations when 'server controlled'

---

tests/test_interpolator.h

In [this commit](https://github.com/GodotNetworking/network_synchronizer/commit/5e5aaca0442d4c5472abc7947a4b0e3b97e32e15), Set was updated to HashSet, but HashMap was forgotten about. The only instances of HashMap were in the tests, so this caused the tests to not build. This PR fixes this by using HashMap in the tests with the new iterators.

Update Map to HashMap in tests

---

networked_controller.cpp

In case when authority over networked_controller has server there is a lot of error prints about rpc not being allowed when server is changing server_controlled mode

check to prevent rpc call to myself in set_server_controlled

---

data_buffer.cpp
data_buffer.h
input_network_encoder.cpp
input_network_encoder.h
networked_controller.cpp
networked_controller.h

This commit add support to implement the NetwokedController class from C++;
also it add the InputNetworkEncoder that can be used to simplify the
character controller implementation.
```c++
// Usually called into the constructor, or during the controller
// initialization. Registers the inputs encoded by `input_encoder`.
uint32_t input_id = input_encoder->register_input(
StringName("move"),
Vector2(), // Default
DataBuffer::DATA_TYPE_NORMALIZED_VECTOR2,
DataBuffer::COMPRESSION_LEVEL_2);
// Usually this is called from `collect_inputs()`.
// It encodes the input_array into the buffer, according to the
// registered inputs.
input_encoder->encode(input_array, r_buffer);
// Usually this is called from `controller_process`.
// It decodes the buffer and put the inputs inside the `input_array`. …
```

Add native code support & InputNetowkEncode.

---

data_buffer.cpp
data_buffer.h
input_network_encoder.cpp
input_network_encoder.h
networked_controller.cpp
networked_controller.h

> Port of: https://github.com/GodotNetworking/network_synchronizer/pull/15
This commit add support to implement the NetwokedController class from C++;
also it add the InputNetworkEncoder that can be used to simplify the
character controller implementation.
```c++
// Usually called into the constructor, or during the controller
// initialization. Registers the inputs encoded by `input_encoder`.
uint32_t input_id = input_encoder->register_input(
StringName("move"),
Vector2(), // Default
DataBuffer::DATA_TYPE_NORMALIZED_VECTOR2,
DataBuffer::COMPRESSION_LEVEL_2);
// Usually this is called from `collect_inputs()`.
// It encodes the input_array into the buffer, according to the
// registered inputs.
input_encoder->encode(input_array, r_buffer);
// Usually this is called from …
```

Add native code support & InputNetowkEncoder.

---

input_network_encoder.h

this way the module path doesn't matter

fix include path to search same dir

---

.gitattributes
.gitignore

Port of #41 to 3.x. This PR adds `*.obj` to the .gitignore and adds a .gitattributes file. These changes help with using this module on Windows. Before I was getting MSVC compilation artifacts showing up in Git.

[3.x] Add *.obj to .gitignore and add .gitattributes

---

networked_controller.cpp

Never process the Doll interpolation untill the epoch is arrived
3.x version: https://github.com/GodotNetworking/network_synchronizer/pull/47

Never process the Doll interpolation untill the epoch is arrived

---

networked_controller.cpp

Never process the Doll interpolation untill the epoch is arrived
4.0 version: https://github.com/GodotNetworking/network_synchronizer/pull/46

 Never process the Doll interpolation untill the epoch is arrived

---

input_network_encoder.cpp

Removing `uint` as it's not a portable godot type

Removing `uint` as it's not a portable godot type

---

net_utilities.cpp
net_utilities.h
networked_controller.cpp
networked_controller.h
scene_synchronizer.cpp

The server was detecting the amount of packets the client should be ahead: this is known as virtual latency and you will find it as `optimal_frame_delay`.
Then the server was calculating how many packets the client was ahead the server `consecutive_inputs`.
The client was receiving an acceleration factor that was calculated using the delta between those two variables and some other logic.
This mechanism was working ok, but due to the imprecise nature of the acceleration algorithm, the client was unable to always produce the correct number of packets.
The  server still fetches `optimal_frame_delay` and `consecutive_inputs`; but this time the delta is right away notified to the client.
Once the client receives the delta, it accelerates exactly that frame count: no more, no less.
Another …

Improved speedup mechanism.

---

net_action_processor.h

It is defined as `struct NodeData {` in `net_utilities.h`, but this forward declaration did not match. This PR fixes it.
Classes and structs are not the same, and they are defined separately in MSVC.
```
modules/network_synchronizer/net_utilities.h:316:1: warning: 'NodeData' defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
struct NodeData {
^
modules/network_synchronizer/net_action_processor.h:7:1: note: did you mean struct here?
class NodeData;
^~~~~
struct
```

Fix `NetUtility::NodeData` struct being forward declared as a class

---

register_types.cpp

A project with the module compiled successfully but would report InputNetworkEncoder as a missing class.

Add missing class InputNetworkEncoder to ClassDB

---

register_types.cpp

A project with the module compiled successfully but would report InputNetworkEncoder as a missing class.

[3.x] Add missing class InputNetworkEncoder to ClassDB

---

scene_synchronizer.cpp

It seems that instead of not having a multiplayer peer when not connected, instead Godot 4 now has a class called OfflineMultiplayerPeer.

Replace peer being null with checks for OfflineMultiplayerPeer

---

debugger_ui/debugger.py
networked_controller.cpp
scene_synchronizer.cpp
scene_synchronizer_debugger.cpp

4.0 version: https://github.com/GodotNetworking/network_synchronizer/pull/68
- This PR makes the NetSync verbose; now the critical parts of the code leave a trace simplifying the process of debugging using the NetSync-debugger.
- On top of that, the debugger (both UI and backend) was changed to store all the processed frame, regardless the frame ID: Under some specific conditions, the net sync may re-process a frame (for example when the input is missing). In all those cases when the frame is processed again, the net sync doesn't override the frame data, rather it created a new iteration: which is now well visible on the UI.
- This PR, contains a small fix on the `fetch_next` function: the `ghost_input_count += 1;` was moved after the input search loop, avoiding to immediately fetch the …

Enhance the NetSync debugger

---

debugger_ui/debugger.py
networked_controller.cpp
scene_synchronizer.cpp
scene_synchronizer_debugger.cpp

Port of: https://github.com/GodotNetworking/network_synchronizer/pull/67
- This PR makes the NetSync verbose; now the critical parts of the code leave a trace simplifying the process of debugging using the NetSync-debugger.
- On top of that, the debugger (both UI and backend) was changed to store all the processed frame, regardless the frame ID: Under some specific conditions, the net sync may re-process a frame (for example when the input is missing). In all those cases when the frame is processed again, the net sync doesn't override the frame data, rather it created a new iteration: which is now well visible on the UI.
- This PR, contains a small fix on the `fetch_next` function: the `ghost_input_count += 1;` was moved after the input search loop, avoiding to immediately fetch the …

Enhances the `NetSync` debugger

---

scene_synchronizer.cpp
scene_synchronizer.h

Port of: https://github.com/GodotNetworking/network_synchronizer/pull/70
This commit allows to client to receive the server snapshot sync even when the local controller doesn't exist.
The InputID generated by the controller is now optinal, when the Controller doesn't exist; in such case the server snapshot is immediately applied while the rewinding mechanism is entirely disabled.
It was necessary to modify the snapshot format: now the `InputID` is stored separately from the controller `NodeData` and moved at the top of the array.
Receiving a corrupted snapshot data was fatal for the client, as the corrupted data were leaking into the buffer, leaving the client unable to function properly. This commit fix that by making sure a separate buffer is used during the snapshot parsing.
The …

Enable scene synchronization without an client Controller.

---

scene_synchronizer.cpp

Port of https://github.com/pahdolabs/network_synchronizer/pull/10/commits/af2b93ea616a4d8a38a7a5b39db4088c34f0aa58
The server Action execution processor was assuming a linear frame counting. However, this assumption is wrong as the server may jump by `N` frames, forward in case the peer is lagging: in that case, the Actions were left behind never executed and an error condition was kept spamming about that Action.
This PR addresses that issue by executing the Action ASAP, even if too late; The error messages got improved too, making them more granular with better description.

Fix the issue caused by lagging peers

---

scene_synchronizer.cpp
scene_synchronizer.h

Port of: https://github.com/pahdolabs/network_synchronizer/pull/11
This commit:
1. Improves the process_controllers_recovery function by splitting it into smaller functions.
2. Fixes a bug: the collected postponed-recovers were ignored in case of large de-sync.
3. Introduces a new event which is triggered when a de-sync is registered and can be used to collect extra data.

Improves the de-sync PCR, adds de-sync event.

---

core/object_data.cpp
core/object_data.h
doc_classes/SceneSynchronizer.xml
godot4/gd_scene_synchronizer.cpp
godot4/gd_scene_synchronizer.h
net_utilities.cpp
net_utilities.h
scene_synchronizer.cpp
scene_synchronizer.h

Aims to implement https://github.com/GodotNetworking/network_synchronizer/issues/86
TODO:
- Test it out properly
- Check if we should be using the -ed form of the word, or sometimes `trickling` in the comments are in some namings

WIP Renamed all `deferred` to `trickled`

---

networked_controller.cpp
networked_controller.h
scene_synchronizer.cpp

This fixes a crash in The Mirror during startup where sometimes the network synchronizer would try to unregister a network controller that belongs to a previously freed scene synchronizer.
For code clarity, the registering and unregistering have been split into separate methods with guard clauses, instead of having one method try to do both operations.

Fix crash when registering network controllers with scene synchronizers

---

register_types.cpp

Added:
- --unit-test-netsync so we can run unit tests optionally
Note: 
This stuff needs ported properly to the latest engine IMO

disable netsync tests in normal startup

---

godot4/gd_scene_synchronizer.cpp
net_utilities.h
scene_synchronizer.cpp
scene_synchronizer.h

Optimizes the function `detect_and_signal_changed_variables`, on the client, by checking only the active objects.
Adds a bunch of `NS_PROFILE_*` macros to profile the NetSync using the Tracy Profiler.

Optimizes the function detect_and_signal_changed_variables.

---

core/net_utilities.h
core/peer_networked_controller.cpp
core/peer_networked_controller.h
core/snapshot.cpp
core/snapshot.h
core/var_data.cpp
scene_synchronizer.cpp
scene_synchronizer.h
tests/test_doll_simulation.cpp
tests/tests.cpp

In the previous implementation the `DollController` was processing the exact same timeline executed by the `PlayerController` and that was causing the doll to runs out inputs forcing it to guess them.
The new approach separates the `DollController` and `PlayerController` timelines, while still processing them together: Allowing the `DollController` not to runs out inputs and preventing jittering.

Fixes the jittering that was possible to observe when the other players moves forward

---

data_buffer.cpp

Casting to `void` is a way to "use" a variable without actually doing anything to it, fixing the warning.

Fix unused variable warning with DEB_READ and DEB_WRITE

---

core/core.cpp
core/core.h
core/net_utilities.h
core/object_data_storage.cpp
core/peer_networked_controller.cpp
core/peer_networked_controller.h
core/snapshot.cpp
godot4/gd_scene_synchronizer.cpp
godot4/input_network_encoder.cpp
scene_synchronizer.cpp
scene_synchronizer.h
tests/test_doll_simulation.cpp
tests/test_netsync_bit_array.h
tests/test_scene_synchronizer.cpp
tests/test_simulation.cpp

This fixes errors like these. Basically it's some weird C++ quirk where we are supposed to use `{{ }}` instead of just `{ }` to avoid a potential ambiguity. This should behave the same as before.
https://stackoverflow.com/questions/31555584/why-is-clang-warning-suggest-braces-around-initialization-of-subobject-wmis
Also included:
- Fix path to `bit_array.h` in tests.
- Fix shadowing variable warnings.
- Fix signed/unsigned warnings, switch a few places to `size_t`.
- Use explicitly named types for brace initializers.
This fixes compiling with warnings, compiling with tests, and compiling for Android.

Fix compile warnings with brace initializers and signed comparisons

---

core/scene_synchronizer_debugger.cpp

This PR fixes compiling with Godot 4.3 beta. @AndreaCatania 
It comes after PackedColorArray so that the cases are in an increasing order.

Add PackedVector4Array to `type_to_string`

---

cmake/CMakeLists.txt
godot4/gd_scene_synchronizer.cpp
scene_synchronizer.cpp
scene_synchronizer.h
tests/local_scene.cpp
tests/local_scene.h
tests/test_doll_simulation.cpp
tests/test_math_lib.cpp
tests/test_math_lib.h
tests/test_simulation.cpp
tests/tests.cpp

When running the tests multiple time was possible to cause them to assert due some desync that happened because of the compensation algorithm that was triggering random desync that were very difficult to control.
The fix was essentially disabling the compensation algorithm (sub_ticks) feature entirely to ensure the test can trigger desync on purpose and verify the recovery mechanism.
Notice, this bug isn't a regression. This was never triggered / detected before and in any case the bug was on the tests not on the code.

Fixes tests

---

core/network_codec.cpp
core/network_codec.h
core/object_data.cpp
core/object_data.h
godot4/gd_scene_synchronizer.cpp
scene_synchronizer.cpp
scene_synchronizer.h
tests/local_network.cpp
tests/local_scene.cpp

The variable type is now statically stored during the variable registration and the encoder can avoid storing it.

The variable type is now statically stored during the variable registration and the encoder can avoid storing it.

---

cmake/CMakeLists.txt
core/bit_array.cpp
core/bit_array.h
core/data_buffer.cpp
core/data_buffer.h
core/ensure.cpp
core/ensure.h
core/net_utilities.cpp
core/net_utilities.h
core/network_interface.h
core/object_data_storage.cpp
core/object_data_storage.h
core/peer_data.cpp
core/peer_data.h
core/peer_networked_controller.cpp
core/peer_networked_controller.h
core/scene_synchronizer_debugger.cpp
core/scene_synchronizer_debugger.h
core/scene_synchronizer_debugger_json_storage.h
debugger_ui/cpplize_debugger.py
debugger_ui/debugger.py
debugger_ui/readme.md
godot4/gd_data_buffer.cpp
godot4/gd_network_interface.cpp
scene_synchronizer.cpp
scene_synchronizer.h
tests/local_network.cpp
tests/local_network.h
tests/test_data_buffer.cpp
tests/test_simulation.cpp

The SceneSynchronizerDebugger was refactored to allow fetching ALL the errors generated by the NetworkSynchronizer at any point by any class.
Removes the debugger singleton, so now it's possible to run both the client and the server on the same process and correctly forward the logs to the right debugger.

Refactors the SceneSynchronizerDebugger

---

core/peer_networked_controller.cpp
core/snapshot.cpp
scene_synchronizer.cpp
scene_synchronizer.h
tests/test_scene_synchronizer.cpp

This PR fixes a bug that was causing the variables marked as "Skip Rewind" not to be set on the client and changes  the way the ScheduledProcedure are handled.
The Scheduled Procedure are information about some process to be executed in future, so doesn't make sense to trigger a rewind if the client didn't receive that info yet since we would rewind for an information that will likely have 0 impact on the current rewind. For this reason now the procedure is restored on the client, if missing, without causing any rewind.
Adds some more integration tests.

Fixes the bug that was preventing the NoRewind vars from being set and improves the ScheduledProcedure restore.
