GameNetworking/NetworkSynchronizer

net_utilities.h, register_types.cpp, scene_synchronizer.cpp
backport of https://github.com/GodotNetworking/network_synchronizer/pull/3
=> Ability to print only error logs

networked_controller.cpp
There is no need to overwrite some methods of NetworkedController when controller is controlled by the server
=> NetworkedController will skip some checks when server controlled

networked_controller.h, scene_synchronizer.h
Removed useless virtual from _notification(int)
=> Removed useless virtual from _notification(int)

networked_controller.cpp, scene_synchronizer.cpp
fixed errors i got when trying to build with Godot's master branch.
=> fix errors

scene_synchronizer.cpp
Port of https://github.com/GodotNetworking/network_synchronizer/pull/23/files
=>  Fix crash: server was not fully cleaning the controlled nodes.

input_network_encoder.h
Port of: https://github.com/GodotNetworking/network_synchronizer/pull/25
=> Improve include path

input_network_encoder.cpp
https://github.com/GodotNetworking/network_synchronizer/issues/26
=> Remove extra input variable.

networked_controller.cpp, networked_controller.h, scene_synchronizer.cpp
3.x version: https://github.com/GodotNetworking/network_synchronizer/pull/36
Add controller_reset event
cc @kubecz3k
=> Add controller_reset event

networked_controller.cpp
Exposes new doll sync settings.
3.x version: https://github.com/GodotNetworking/network_synchronizer/pull/38
=> Exposes new doll sync settings.

net_utilities.h, networked_controller.cpp, scene_synchronizer.cpp
Add support to Tracy
Here the Godot 4.0 version https://github.com/GodotNetworking/network_synchronizer/pull/51
=> Add support to Tracy

net_utilities.h, networked_controller.cpp, scene_synchronizer.cpp
Here the godot 3.5 version https://github.com/GodotNetworking/network_synchronizer/pull/50/files
=> Add support to tracy profiler.

.gitignore, SCsub, data_buffer.cpp, data_buffer.h, debugger_ui/cpplize_debugger.py, debugger_ui/debugger.py, debugger_ui/readme.md, net_action.cpp, net_action.h, networked_controller.cpp, register_types.cpp, scene_synchronizer.cpp, scene_synchronizer.h, scene_synchronizer_debugger.cpp, scene_synchronizer_debugger.h
This PR introduces a debugging tool that gives a lot of information about the networking.
Here the 4.0 version: https://github.com/GodotNetworking/network_synchronizer/pull/56
The reason why this tool was primary implemented was because it was really hard to debug networking issues just by looking at the log output. This tool enables a much more effective way to debug and take insights about the net code.
https://github.com/GodotNetworking/network_synchronizer/wiki/How-to-debug-your-game-net-code
=> Implemented the net sync debugger.

.gitignore, SCsub, data_buffer.cpp, data_buffer.h, debugger_ui/cpplize_debugger.py, debugger_ui/debugger.py, debugger_ui/readme.md, net_action.cpp, net_action.h, networked_controller.cpp, register_types.cpp, scene_synchronizer.cpp, scene_synchronizer.h, scene_synchronizer_debugger.cpp, scene_synchronizer_debugger.h
This PR introduces a debugging tool that gives a lot of information about the networking.
Port of: https://github.com/GodotNetworking/network_synchronizer/pull/55
The reason why this tool was primary implemented was because it was really hard to debug networking issues just by looking at the log output. This tool enables a much more effective way to debug and take insights about the net code.
https://github.com/GodotNetworking/network_synchronizer/wiki/How-to-debug-your-game-net-code
=> Implemented the NetSync debugger.

register_types.cpp, scene_synchronizer.cpp
Suppress warning & add more info.
=> Suppress warning & add more info.

debugger_ui/debugger.py, networked_controller.cpp, scene_synchronizer.cpp, scene_synchronizer_debugger.cpp, scene_synchronizer_debugger.h
- Resolved Debugger UI crash when a frame data is missing.
- Added more debugging prints
- Implemented log indexing
=> Debugger improved.

icons/NetworkedController.svg
=> Add NetworkedController icon.

scene_synchronizer.cpp
Port of: https://github.com/pahdolabs/network_synchronizer/pull/10/commits/af2b93ea616a4d8a38a7a5b39db4088c34f0aa58
The server Action execution processor was assuming a linear frame counting.
However, this assumption is wrong as the server may jump by `N` frames,
forward in case the peer is lagging: in that case, the Actions were left
behind never executed and an error condition was kept spamming about
that Action.
This PR addresses that issue by executing the Action ASAP, even if too
late; The error messages got improved too, making them more granular
with better description.
=>  Fix the issue caused by lagging peers

networked_controller.cpp
Port of https://github.com/pahdolabs/network_synchronizer/pull/12
=> Add missing inputs and speedup-adj event.

net_utilities.cpp, net_utilities.h, networked_controller.cpp, networked_controller.h, register_types.cpp, scene_synchronizer.cpp, scene_synchronizer.h, snapshot.cpp, snapshot.h
This PR contains a bunch of commits that:
- Simplify the code by removing a bunch of code duplication.
- Adds new features to add custom data into the snapshot
- Improves the SyncGroup API
=> Code simplification and new features

config.py, doc_classes/DataBuffer.xml, doc_classes/InputNetworkEncoder.xml, doc_classes/NetworkedController.xml, doc_classes/SceneDiff.xml, doc_classes/SceneSynchronizer.xml
Avoids diffs when running doctool on projects using this module.
=> Generate documentation XML files

core/core.h, core/network_codec.cpp, core/network_codec.h, core/network_interface.h, core/object_data.cpp, core/object_data.h, core/var_data.cpp, core/var_data.h, data_buffer.cpp, data_buffer.h, godot4/gd_network_interface.cpp, godot4/gd_network_interface.h, godot4/gd_networked_controller.cpp, godot4/gd_networked_controller.h, godot4/gd_scene_synchronizer.cpp, godot4/gd_scene_synchronizer.h, net_utilities.cpp, net_utilities.h, networked_controller.cpp, networked_controller.h, scene_synchronizer.cpp, scene_synchronizer.h, snapshot.cpp, snapshot.h, tests/local_network.cpp, tests/local_network.h
This PRs optimizes the way the RPCs are networked and make them much safer by improving the interface.
=> Optimizes the RPC calls

data_buffer.cpp, data_buffer.h, tests/test_data_buffer.cpp, tests/test_data_buffer.h, tests/test_netsync_data_buffer.h, tests/tests.cpp
Fixed DataBuffer string encoding adds u16string encoding.
=> Fixed DataBuffer string encoding adds u16string encoding.

scene_synchronizer.cpp
Fix remaining deferred to trickled
Supersede https://github.com/GameNetworking/network_synchronizer/pull/90
=> Fix remaining deferred to trickled

config.py, doc_classes/DataBuffer.xml, doc_classes/GdNetworkedController.xml, doc_classes/GdSceneSynchronizer.xml, doc_classes/SceneDiff.xml, scene_synchronizer.h
The classes in this repo have changed, but the docs were not correspondingly updated.
=> Update documentation XML files and delete broken SceneDiff references

core/object_data.h, data_buffer.cpp, data_buffer.h, godot4/gd_scene_synchronizer.cpp, godot4/gd_scene_synchronizer.h, net_utilities.cpp, net_utilities.h, networked_controller.cpp, networked_controller.h, scene_synchronizer.cpp, scene_synchronizer.h, tests/local_network.cpp, tests/test_doll_simulation.cpp, tests/test_doll_simulation.h, tests/test_simulation.cpp, tests/tests.cpp
=> Add ping mechanism

tests/local_scene.cpp
Deregister the ObjectData when the LocalObject is destroyied.
=> Deregister the ObjectData when the LocalObject is destroyied.

doc_classes/GdSceneSynchronizer.xml, godot4/gd_networked_controller.cpp, godot4/gd_networked_controller.h, godot4/gd_scene_synchronizer.cpp, godot4/gd_scene_synchronizer.h, networked_controller.cpp, networked_controller.h, scene_synchronizer.cpp, scene_synchronizer.h, tests/local_scene.cpp, tests/test_doll_simulation.cpp, tests/test_scene_synchronizer.cpp, tests/test_simulation.cpp
It's not anylonger required to process the NetSync with fixed delta time.
Now the NetSync can be processed on the normal tick rate (with variable
delta time) allowing it to be much responsive than before.
It will take care to process with fixed delta time the components that
needs that.
=> Made the NetSync much responsive than before.

core/ensure.h, core/object_data.cpp, core/object_data.h, core/peer_networked_controller.cpp, core/peer_networked_controller.h, core/snapshot.cpp, core/snapshot.h, godot4/gd_scene_synchronizer.cpp, scene_synchronizer.cpp, scene_synchronizer.h
Prepares the NetSync to resolve the doll jittering issue
=> Prepares the NetSync to resolve the doll jittering issue

doc_classes/DataBuffer.xml, doc_classes/GdSceneSynchronizer.xml, doc_classes/InputNetworkEncoder.xml
This avoids diffs when running doctool. Note: This PR expects Godot 4.2 or later (removes `version="4.1"`).
=> Run doctool

core/net_utilities.cpp, core/net_utilities.h, godot4/gd_scene_synchronizer.cpp, godot4/gd_scene_synchronizer.h, scene_synchronizer.cpp, scene_synchronizer.h
Removes LocalVector from scene_synchronizer.h/cpp
=> Removes LocalVector from scene_synchronizer.h/cpp

godot4/gd_scene_synchronizer.cpp, scene_synchronizer.cpp, scene_synchronizer.h
Removes OS and ProjectSettings from scene_sync.
=> Removes OS and ProjectSettings from scene_sync.

core/scene_synchronizer_debugger.cpp, core/scene_synchronizer_debugger.h, core/var_data.h, godot4/gd_scene_synchronizer.cpp, godot4/gd_scene_synchronizer.h, register_types.cpp
Abstracts the file system access.
=> Abstracts the file system access.

core/bit_array.cpp, core/bit_array.h, core/network_codec.cpp, core/network_codec.h, core/peer_networked_controller.cpp, core/peer_networked_controller.h, data_buffer.cpp, godot4/gd_network_interface.cpp, scene_synchronizer.cpp, scene_synchronizer.h, tests/local_network.cpp
Removes LocalVector usage from PeerNetController - Removes Vector from rpc usage and abstracts BitArray
=> Removes LocalVector usage from PeerNetController - Removes Vector from rpc usage and abstracts BitArray

core/peer_networked_controller.cpp
Fixes the bug introduced by 50c10d1
=> Fixes the bug introduced by 50c10d1

core/bit_array.cpp, core/object_data.cpp, core/object_data.h, core/snapshot.cpp, core/snapshot.h, godot4/gd_scene_synchronizer.cpp, scene_synchronizer.cpp, scene_synchronizer.h, tests/test_doll_simulation.cpp, tests/test_scene_synchronizer.cpp, tests/test_simulation.cpp
Integrates the synch of the controlled by peer.
=> Integrates the synch of the controlled by peer.

cmake/CMakeLists.txt, core/net_utilities.cpp, core/net_utilities.h, core/object_data.cpp, core/object_data_storage.cpp, core/peer_networked_controller.cpp, core/scene_synchronizer_debugger.cpp, core/scene_synchronizer_debugger.h, core/snapshot.cpp, scene_synchronizer.cpp, scene_synchronizer.h, tests/local_scene.cpp, tests/local_scene.h, tests/test_data_buffer.cpp, tests/test_scene_synchronizer.cpp, tests/test_switch_controller.cpp, tests/test_switch_controller.h, tests/tests.cpp
Fixes several bugs + Optimizes the snapshot encoding + Some other improvements.
=> Fixes several bugs + Optimizes the snapshot encoding + Some other improvements.

cmake/CMakeLists.txt, core/peer_data.cpp, core/peer_networked_controller.cpp, core/peer_networked_controller.h, scene_synchronizer.cpp, tests/test_AI_simulation.cpp, tests/test_AI_simulation.h, tests/test_doll_simulation.cpp, tests/tests.cpp
=> Add support to AI Controllers

core/peer_networked_controller.cpp, core/peer_networked_controller.h, scene_synchronizer.cpp, scene_synchronizer.h, tests/test_scene_synchronizer.cpp
Fixes some bugs related to the virtual latency and frames input buffers
=> Fixes some bugs related to the virtual latency and frames input buffers
